# Site settings
title: Lisper.in
email: mail@chaitanyagupta.com
description: Thoughts on programming from a Lisper
baseurl: ""
url: "http://lisper.in"
twitter_username: chaitanya_gupta
github_username:  chaitanyagupta

# Build settings
markdown: redcarpet

redcarpet:
  extensions: [with_toc_data]
