# Site settings
title: Lisper.in
email: mail@chaitanyagupta.com
description: Essays on programming, technology and other things
baseurl: ""
url: https://lisper.in
twitter_username: chaitanya_gupta
github_username:  chaitanyagupta

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed

# Feeds
feed:
  categories:
    - lisp

