# Site settings
title: Lisper.in
email: mail@chaitanyagupta.com
description: Thoughts on programming
baseurl: ""
url: "http://lisper.in"
twitter_username: chaitanya_gupta
github_username:  chaitanyagupta

# Build settings
markdown: kramdown
highlighter: rouge
